=== dfleta/XML_teoria/ejemploXMLconSchemaMio/vueloSchema_ns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="unqualified"
	targetNamespace="http://www.edreams.com"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.edreams.com">

	<xs:element name="vuelo"><!-- elemento global -->
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="billete"
					type="tipoBillete">
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<!-- definición de tipos complejos -->


	<xs:complexType name="tipoBillete">
		<xs:sequence>
			<xs:element name="trayecto" type="tipoTrayecto"></xs:element>
			<!-- elementos locales -->
			<xs:element name="fecha" type="tipoFecha"></xs:element>
			<xs:element name="pasajeros" type="tipoPasajeros"></xs:element>
			<xs:element name="clase" type="tipoClase"
				form="qualified">
			</xs:element>
		</xs:sequence>
		<!-- atributos de "billete", tras etiqueta "sequence" -->
		<xs:attribute name="id" type="xs:unsignedLong"
			form="qualified">
		</xs:attribute>
	</xs:complexType>


	<xs:complexType name="tipoTrayecto">
		<xs:sequence>
			<xs:element name="origen" type="xs:string"></xs:element>
			<xs:element name="destino"><!-- elemento con contenido simple (string) y atributo -->
				<xs:complexType>
					<xs:simpleContent><!-- contenido simple -->
						<xs:extension base="xs:string">
							<xs:attribute name="did" type="xs:string"></xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:choice>
				<xs:element name="ida"><!-- elemento vacío: es complejo -->
					<xs:complexType></xs:complexType>
				</xs:element>
				<xs:element name="vuelta">
					<xs:complexType></xs:complexType>
				</xs:element>
				<xs:element name="idayvuelta">
					<xs:complexType></xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipoFecha">
		<xs:sequence>
			<xs:element name="salida" type="xs:date"></xs:element>
			<xs:element minOccurs="0" name="regreso" type="xs:date"></xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="tipoPasajeros">
		<xs:sequence>
			<xs:element name="adultos" type="pasajerosAdultos"></xs:element>
			<xs:element maxOccurs="1" minOccurs="0" name="niños"
				type="pasajerosMenores">
			</xs:element>
			<xs:element maxOccurs="1" minOccurs="0" name="bebes"
				type="pasajerosMenores">
			</xs:element>
		</xs:sequence>
	</xs:complexType>



	<!-- definición de tipos simples -->

	<xs:simpleType name="tipoClase">
		<xs:restriction base="xs:string">
			<xs:enumeration value="turista barata"></xs:enumeration>
			<xs:enumeration value="turista"></xs:enumeration>
			<xs:enumeration value="business"></xs:enumeration>
			<xs:enumeration value="primera"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="pasajerosAdultos">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"></xs:minInclusive>
			<xs:maxInclusive value="9"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="pasajerosMenores">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[0-9]"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>


	<!-- tipo derivado: extensión de tipos complejos -->

	<xs:complexType name="extTipoPasajeros">
		<xs:complexContent>
			<xs:extension base="tipoPasajeros">
				<xs:sequence>
					<xs:element name="bichos" type="xs:integer"></xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

</xs:schema>

=== dfleta/XML_teoria/ejemploXMLconSchemaMio/automatico.xml
<?xml version="1.0" encoding="UTF-8"?>
<edreams:vuelo xmlns:edreams="http://www.edreams.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.edreams.com vueloSchema_ns.xsd ">
	<billete edreams:id="0">
		<trayecto>
			<origen>origen</origen>
			<destino did="">destino</destino>
			<ida />
		</trayecto>
		<fecha>
			<salida>2001-01-01</salida>
			<regreso>2001-01-01</regreso>
		</fecha>
		<pasajeros xsi:type="edreams:tipoPasajeros">
			<adultos>1</adultos>
			<niÃ±os>0</niÃ±os>
			<bebes>0</bebes>
		</pasajeros>
		<edreams:clase>turista barata</edreams:clase>
	</billete>
</edreams:vuelo>

=== dfleta/XML_teoria/ejemploXMLconSchemaMio/ficheroXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:vuelo xmlns:p="http://www.edreams.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.edreams.com vueloSchema_ns.xsd ">
	<billete>
		<trayecto>
			<origen>origen</origen>
			<destino>destino</destino>
			<ida />
		</trayecto>
		<fecha>
			<salida>2001-01-01</salida>
		</fecha>
		<pasajeros>
			<adultos>3</adultos>
		</pasajeros>
		<clase>turista barata</clase>
	</billete>
</p:vuelo>

=== dfleta/XML_teoria/ejemploXMLconSchemaMio/vueloSchema_ns.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:vuelo xmlns:p="http://www.edreams.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.edreams.com vueloSchema_ns.xsd ">
	<billete id="0">
		<trayecto>
			<origen>origen</origen>
			<destino did="">destino</destino>
			<ida />
		</trayecto>
		<fecha>
			<salida>2001-01-01</salida>
			<regreso>2001-01-01</regreso>
		</fecha>
		<pasajeros>
			<adultos>1</adultos>
			<niÃ±os>0</niÃ±os>
			<bebes>0</bebes>
		</pasajeros>
		<clase>turista barata</clase>
	</billete>
</p:vuelo>
